### ISSUE TITLE
Create Protection job for Physical servers

### ISSUE THREAD

**Issue by einarbey** [cohesity/cohesity-powershell-module#110]
## 🚀 Feature Request

Hi,

I am trying to create script to create new protection job for file backup on physical aix server but looks like I am unable to do so with powershell script it always asks for vCenter "Please specify the VCenter for the Protection Job"

I tried with both -ParentSourceId and -SourceIds

also there is missing feature for exclude file paths 

## Example or reference 

small part of the script I am using to create new Protection Job
### Create New Protection Job ###
New-CohesityProtectionJob -Name $ProtectionJobName `
    -SourceIds $SourceID.Id `
    -Description $DescriptionPortectionJob `
    -PolicyId $GetPolicyID.Id `
    -Environment $EnvironmentTypeUse `
    -StorageDomainId $StorageDomainID.Id `
    -Timezone "Atlantic/Reykjavik" `
    -ScheduleStartTime "1/12/2020 11:00:00 PM"

**Comment by ashish-cohesity** [comment]
Ack @einarbey  , we are looking into this.

**Comment by bijayprasadtiwari** [comment]
Created a cmdlet 'New-CohesityPhysicalServerProtectionJob', the cmdlet shall protect both blocks and files.

As per the github ticket the customer had asked for updating the exclude file path. It can be achieved by using the cmdlet 'Set-CohesityProtectionJob'

The fix will be available in the upcoming release.

**Comment by bijayprasadtiwari** [comment]
The fix is available in v1.5.0.
