### ISSUE TITLE
Connect-CohesityCluster -  ignore SSL certificate check ?

### ISSUE THREAD

**Issue by sdupuy** [cohesity/cohesity-powershell-module#131]
## ❓ Questions and Requests

Hi,

Is there a way to ignore SSL certificate check while using Connect-CohesityCluster ?

We are currently using a self signed certificat and I cannot connect with powershell :
```
The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
```

For example, the cmdlet Connect-VIServer from VMware does not care of invalid certificate.

Sylvain

**Comment by pyashish** [comment]
@bijayprasadtiwari  can you take a look at this ?

**Comment by bijayprasadtiwari** [comment]
Let me have a look into it.

**Comment by bijayprasadtiwari** [comment]
@sdupuy , can you delete $HOME/.cohesity, and make a fresh attempt, and ensure that the flag "AllowInvalidServerCertificates" is set to "true" in $HOME/.cohesity

**Comment by bijayprasadtiwari** [comment]
@sdupuy,  We are working on it, to reproduce the issue, can you share the certificate details and the cluster version.

**Comment by pyashish** [comment]
@sdupuy  did this solve this issue ?

**Comment by pyashish** [comment]
Closing this issue for now. Will re-visit this with future plugins.
