### ISSUE TITLE
Unable to Start-Job for A DirectCloud Job

### ISSUE THREAD

**Issue by salmeida77** [cohesity/cohesity-powershell-module#137]
When I launch Start-CohesityProtectionJob to a DirectCloud Job, I got "Protection job was started successfully." but nothing happens.

Start-CohesityProtectionJob -Id 70127
Protection job was started successfully.

Maybe I got to use "-CopyRunTargets" parameter, but I don't know how to use it.

**Comment by pyashish** [comment]
Hi @salmeida77  , thanks for the question. When you say DirectCloud Job, is it archival job/CopyRun ? 

@bijayprasadtiwari  , can you please help with an example. Also update the documentation.

```Get-Help Start-CohesityProtectionJob -full```

**Comment by bijayprasadtiwari** [comment]
@salmeida77 , please check the sample at https://github.com/cohesity/cohesity-powershell-module/blob/master/samples/ProtectionJobRun/StartJobWithCopyRunTargets.ps1 . Let me know if that helps.

**Comment by bijayprasadtiwari** [comment]
Please reopen if the issue persist.
