### ISSUE TITLE
Restore from Archive not working

### ISSUE THREAD

**Issue by lorenzstorm1** [cohesity/cohesity-powershell-module#138]
Restore-CohesityVMwareVM is working fine for restores that are stored locally on the system but is not working for restores where the backup is only available on the archive storage:

Restore-CohesityVMwareVM -TaskName "RestoreTest2" -VmNamePrefix "RestoreTest-" -DisableNetwork -JobId 2947 -SourceId 497 -JobRunId 12640 -StartTime 1610308801470347

Invoke-WebRequest : {"errorCode":"KInternalError","message":"No finished backup run exists with specified start time 1610308801470347. It may have been garbage 
collected"}

**Comment by bijayprasadtiwari** [comment]
@lorenzstorm1 , thanks for pointing out. We will have a look into it and revert back.

**Comment by bijayprasadtiwari** [comment]
@lorenzstorm1 , can you check if the backup has expired or deleted.

**Comment by lorenzstorm1** [comment]
The Snapshot is deleted from local Cohestiy but still on the S3 Archive. Get-CohesityProtectionJobRun outputs the Snapshort as deleted

**Comment by bijayprasadtiwari** [comment]
Use the cmdlet Restore-CohesityVMwareVM with the flag SourceArchivalId to restore from archival.
FYR, https://cohesity.github.io/cohesity-powershell-module/#/cmdlets-reference/restore-cohesityvmwarevm?id=restore-cohesityvmwarevm


A new release for cohesity powershell SDK v1.6.8 is available at https://github.com/cohesity/cohesity-powershell-module/releases/tag/v1.6.8 and https://www.powershellgallery.com/packages/Cohesity.PowerShell/1.6.8


Do let us know if you have any feedback.
