### ISSUE TITLE
Get-CohesityProtectionJob does not output ProtectionJob objects

### ISSUE THREAD

**Issue by aaronmcdavid** [cohesity/cohesity-powershell-module#140]
## 🐛 Bug Report

Get-CohesityProtectionJob outputs an array of custom objects instead of an array of ProtectionJob objects.

## Expected behavior

This is a change from at the latest, v1.0.12, when ProtectionJob objects were output.  In general, the output of the Get- cmdlets ought be `IEnumerable<ModelType>`.

## Actual Behavior

Curiously, the script bolts on a TypeName of System.Object#ProtectionJob instead of actually using the ProtectionJob type.

**Comment by pyashish** [comment]
@aaronmcdavid , we recently moved from C# based cmdlets to script based cmdlets. That might have caused this change. Adding Bijay to comment more and see if we can preserve previous behavior.

**Comment by bijayprasadtiwari** [comment]
Thanks @aaronmcdavid for raising the issue. @pyashish the behavior that you have observed, because we have moved from C# based cmdlet to script based. We understand your concern and we will investigate how we can preserve the cmdlet behavior.

**Comment by aaronmcdavid** [comment]
Understood.  I've got a good number of modules that output C# model types from PS code.  I do it by referencing the compiled .dll in the .psd1 file, for example:
`RequiredAssemblies = @(
	'.\lib\Corp.Corporate.Types.dll'
)`

And then the script portion is loaded as a nested module:
`NestedModules = @(
	'.\SMRH.Corporate.psm1'
)`

It looks like you guys are doing it differently, as Get-CohesityProtectionJob.ps1 already references model types.

You may also consider doing what vmware has done:  they export type Interfaces and encourage everyone to program with the Interfaces, so that they can support multiple different versions of the underlying objects.  That way, as their API grows and changes, it doesn't break legacy code.

I hope you guys decide to stick with C# for version 2!

**Comment by bijayprasadtiwari** [comment]
@aaronmcdavid , sorry for the delayed response. We will have an answer by 23-March-2021, how are we going to approach to resolve this issue. Please bear with us.

**Comment by bijayprasadtiwari** [comment]
@aaronmcdavid , I have communicated our approach in a separate email to Rajesh. He will reach out to you. Do let me know your feedback.
