### ISSUE TITLE
The SSL connection could not be established.

### ISSUE THREAD

**Issue by kesonc** [cohesity/cohesity-powershell-module#146]
Hi , 

I can not connect cohesity with Powershell 7.1.3 , but 5.1 is fine.

My Envorinment : Windows 10 + PowerShell 7.1.3 + Cohesity 6.5.1d

=================
with IP Address：
PS C:\Users\user> Connect-CohesityCluster -Server 192.168.xx.xx

cmdlet Connect-CohesityCluster at command pipeline position 1
Supply values for the following parameters:
Credential
User: admin
Password for user admin: ********

Connect-CohesityCluster: Failed to connect to the Cohesity Cluster
The SSL connection could not be established, see inner exception.
The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors

=================
with FQDN：

PS C:\Users\user> Connect-CohesityCluster -Server cohesitypoc.xxx.local

cmdlet Connect-CohesityCluster at command pipeline position 1
Supply values for the following parameters:
Credential
User: admin
Password for user admin: ********

Connect-CohesityCluster: Failed to connect to the Cohesity Cluster
The SSL connection could not be established, see inner exception.
The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot

**Comment by bijayprasadtiwari** [comment]
@kesonc , ACK we are having a look and revert back ASAP.

**Comment by bijayprasadtiwari** [comment]
The powershell 7.1.3 is a core version. (Please confirm using $PSVersionTable)
If its core, can you cleanup Cohesity.Powershell from powershell 5.1 and install Cohesity.Powershell.Core  and let us know if you still see the issue.

**Comment by kesonc** [comment]
Hi , 

 

Yes , 7.1.3 is a core version.

After reinstall Core Version , it works.

Many thanks !!

**Comment by kesonc** [comment]
Sorry , another problem , when get a DataLock view , it return a error.
Because expiryTimestampMsecs it too large for an Int32.

Get-CohesityView: JSON integer 1616601599000 is too large or small for an Int32. Path 'views[79].fileLockConfig.expiryTimestampMsecs', line 1, position 103250.

**Comment by bijayprasadtiwari** [comment]
OK, we will make the necessary changes and keep you posted.

**Comment by bijayprasadtiwari** [comment]
We have made the changes and a new release for cohesity powershell SDK v1.6.8 is available at https://github.com/cohesity/cohesity-powershell-module/releases/tag/v1.6.8 and https://www.powershellgallery.com/packages/Cohesity.PowerShell/1.6.8
