### ISSUE TITLE
Get-CohesityProtectionJobRun throws error when job name is a subset of another job

### ISSUE THREAD

**Issue by toddcae1** [cohesity/cohesity-powershell-module#147]
## 🐛 Bug Report

After upgrading from v1.0.11 to v1.6.5 of the Cohesity powershell module, a batch job that checks on the status of all of our active jobs started to fail. I traced the failure to the call being made to the function **Get-CohesityProtectionJobRun**. 

Looking at the code for **Get-CohesityProtectionJobRun** I found the underlying issue is due to how **Get-CohesityProtectionJob** handles job names, specifically jobs names that are subsets of one another. The -names parameter of **Get-CohesityProtectionJob** appears to be using [job name]* wildcard type of pattern matching instead of an exact match of "[job name]".

This may now be expected behavior for **Get-CohesityProtectionJob**, since the parameter -names is plural, but when this function is called from within **Get-CohesityProtectionJobRun** the script fails due to multiple records being returned due to the afore mentioned pattern matching.

Ex. 

If I have two jobs, one named JOB1 and one named JOB1_Archive, a call to **Get-CohesityProtectionJobRun** breaks when trying to get details for just "JOB1".

> PS C:\WINDOWS\system32>Get-CohesityProtectionJobRun -JobName "JOB1" -RunTypes "kRegular" -StartTime 1616394684987644
> Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Int64".
> At C:\Program Files\WindowsPowerShell\Modules\Cohesity.PowerShell\1.6.5\Scripts\ProtectionJobRun\Get-CohesityProtectionJobRun.ps1:87 char:13
> ++             $JobId = $jobObject.id
> ++             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
>     + FullyQualifiedErrorId : ConvertToFinalInvalidCastException
> 

Looking at the ps1 script for file **Get-CohesityProtectionJobRun** I can see  $jobObject is populated from:

> $jobObject = Get-CohesityProtectionJob -Names $JobName

If I directly pass my job name to **Get-CohesityProtectionJob** I get two rows back when only one row should be returned:

> PS C:\WINDOWS\system32> Get-CohesityProtectionJob -Names "JOB1"
> 
> Id     Name                Environment LastRunTime          SLA  IsPaused
> --     ----                ----------- -----------          ---  --------
> 414993 JOB1                kVMware     3/21/2021 4:00:00 PM Pass False
> 415030 JOB1_Archive        kVMware     3/21/2021 7:00:00 PM Pass False

Renaming "JOB1" so that is is not a subset of another job name could possibly fix this, but then I would expect Cohesity to have logic in place that would prevent names to be subsets of one another when a job is created (or renamed).

**Comment by bijayprasadtiwari** [comment]
@toddcae1, thanks for pointing out the bug, we will validate and make a fix in v1.6.6

**Comment by bijayprasadtiwari** [comment]
The bug has been fixed. A new release for the cohesity powershell SDK v1.6.6 is available at https://github.com/cohesity/cohesity-powershell-module/releases/tag/v1.6.6 and https://www.powershellgallery.com/packages/Cohesity.PowerShell/1.6.6

Do let us know your feedback. Closing this issue, reopen if required.

**Comment by toddcae1** [comment]
The version 1.6.6 release has fixed the issue I was running into. Thank you.
