### ISSUE TITLE
get-cohesityprotectionJob 

### ISSUE THREAD

**Issue by pizzingrilli** [cohesity/cohesity-powershell-module#150]
Running the get-cohesityprotection command without parameters gets an error message

Get-CohesityProtectionJob : Error converting value "kWarning" to type 'System.Nullable`1[Cohesity.Model.BackupRun+StatusEnum]'. Path '[3].lastRun.backupRun.status', line 1, position 19456.
At line:1 char:1 

Is this a known issue?

**Comment by bijayprasadtiwari** [comment]
We have the latest SDK v1.6.7 available, can you update and let use know if you are still facing the issue.

**Comment by pizzingrilli** [comment]
Same issue with 1.6.7

**Comment by bijayprasadtiwari** [comment]
OK, can you cleanup all the preceding versions and freshly launch the powershell window.

**Comment by pizzingrilli** [comment]
This was the problem....thx
