### ISSUE TITLE
New-CohesityProtectionJob : Parameter set cannot be resolved using the specified named parameters.

### ISSUE THREAD

**Issue by DavidSeaton** [cohesity/cohesity-powershell-module#155]
## 🐛 Bug Report

Getting error message when attempting to run command New-CohesityProtectionJob, even without any Parameters set.

Provide better feedback about missing parameters and which specific parameters maybe failing.

## To Reproduce
1. Run the command New-CohesityProjectionJob without any parameters will give ERROR.
> New-CohesityProjectionJob
```
New-CohesityProtectionJob : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ New-CohesityProtectionJob
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-CohesityProtectionJob], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Cohesity.Powershell.Cmdlets.ProtectionJob.NewCohesityProtectionJob
```

2. Run the command New-CohesityProjectionJob with parameters will still give ERROR
> New-CohesityProtectionJob -Name "MyName" -Description "My Description" -PolicyId "1234567890" -Timezone "America/New_York" -ScheduleStartTime "05/11/2021 05:00 AM" -StorageDomainName DefaultStorageDomain -FullSLATimeInMinutes 210 -IncrementalSLATimeInMinutes 150 -Environment kAcropolis -ParentSourceId 1
```
New-CohesityProtectionJob : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ New-CohesityProtectionJob -Name "ba" -Description "A" -PolicyId "6911 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-CohesityProtectionJob], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Cohesity.Powershell.Cmdlets.ProtectionJob.NewCohesityProtectionJob
```

## Expected behavior

One would expect to either receive errors with on specific Parameters. At the very least tell if any parameters were given.

## Actual Behavior

Same error code, no matter what is provided.
![New-CohesityProtectionJob-Failing](https://user-images.githubusercontent.com/58090089/117881528-50b7b080-b277-11eb-8eb9-866ce65ba6c8.png)

**Comment by pyashish** [comment]
Ack David. We will look into this.

**Comment by bijayprasadtiwari** [comment]
@DavidSeaton , thanks for pointing it out. We are having a look into it and see if the cmdlet can tell the user about the invalid parameters. For your reference please have a look into https://cohesity.github.io/cohesity-powershell-module/#/cmdlets-reference/new-cohesityprotectionjob?id=new-cohesityprotectionjob
 

Meanwhile the parameter (StorageDomainName) to the cmdlet is incorrect.

**Comment by bijayprasadtiwari** [comment]
@DavidSeaton , The default parameter set was not configured for New-CohesityProtectionJob, therefore you were seeing the issue. Made the fix, pushed the code to github and it will be available in the upcoming release.
![image](https://user-images.githubusercontent.com/43197022/118959935-649e9900-b980-11eb-941f-9a71068a3592.png)

**Comment by bijayprasadtiwari** [comment]
The fix is available at https://www.powershellgallery.com/packages/Cohesity.PowerShell/1.6.9. Closing the ticket, do reopen if the bug is not fixed.
