### ISSUE TITLE
Register-CohesityProtectionSourceAcropolis fails with correct Authentication

### ISSUE THREAD

**Issue by DavidSeaton** [cohesity/cohesity-powershell-module#156]
## 🐛 Bug Report

When attempting to Register a Nutanix Acropolis system, the process fails.

This process should work as information given during process is correct.

## To Reproduce

(Write your steps here:)

1. Run the Register Command.
>  Register-CohesityProtectionSourceAcropolis -Server $SourceHostname -Credential (Get-Credential)
2. Provide Credentials when prompted.

## Expected behavior

Should see command execution successful.

## Actual Behavior

Process fails to with general error.
```
Register-CohesityProtectionSourceAcropolis : Could not populate incoming entity protos
At C:\repo\cohesity_ps\Cohesity-SetSource.ps1:19 char:6
+      Register-CohesityProtectionSourceAcropolis -Server $SourceHostna ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Register-Cohesi...SourceAcropolis], Exception
    + FullyQualifiedErrorId : System.Exception,Cohesity.Powershell.Cmdlets.ProtectionSource.RegisterCohesityProtectionSourceAcropolis
```
![Register-CohesityProtectionSourceAcropolis-Fail](https://user-images.githubusercontent.com/58090089/117885538-f5d48800-b27b-11eb-8dfc-05dc122bc112.png)

**Comment by pyashish** [comment]
Thanks David, we got escalations from Support and we are looking into this.

**Comment by bijayprasadtiwari** [comment]
@DavidSeaton , we have made a fix and the code has been pushed to github. The fix will be available in the upcoming release.
Below steps were followed to ensure that the AHV protection source works as expected. Please note, that a new attribute is introduced "EntityType" with a default value "KStandaloneCluster" in the cmdlet "Register-CohesityProtectionSourceAcropolis"

Register-CohesityProtectionSourceAcropolis -Server "ahv-cluster"  -Credential (New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList "admin", (ConvertTo-SecureString -AsPlainText 'passsword' -Force))

New-CohesityProtectionJob -Name job-ahv -StorageDomainId 5 -PolicyId 426644075588690:1611300700859:3 -SourceIds 9 -ParentSourceId 1 -Environment KAcropolis

Start-CohesityProtectionJob -Id 17395

Stop-CohesityProtectionJob -Id 17395

Get-CohesityProtectionJobRun -JobId 17395

Get-CohesityProtectionJob -Ids 17395

**Comment by bijayprasadtiwari** [comment]
The fix is available at https://www.powershellgallery.com/packages/Cohesity.PowerShell/1.6.9. Closing the ticket, do reopen if the bug is not fixed.
