### ISSUE TITLE
Time Zone issue with new-CohesityHypervProtectionJob

### ISSUE THREAD

**Issue by ThomasWilla** [cohesity/cohesity-powershell-module#161]
## 🐛 Bug Report

Time Zone with (get-TimeZone).id in new-CohesityHypervProtectionJob not working in Europe (in case of Switzerland)

We have to set the Time Zone "Europe/Zurich" then it works

## To Reproduce

(Write your steps here:)

1. Create a  new-CohesityHypervProtectionJob without Time Zone
2.
3.

**Comment by bijayprasadtiwari** [comment]
@ThomasWilla , thanks for raising the bug, we are looking into it.

**Comment by bijayprasadtiwari** [comment]
@ThomasWilla , we have made a fix and we have a new cohesity powershell SDK v1.7.2 release available at https://github.com/cohesity/cohesity-powershell-module/releases/tag/v1.7.2 and https://www.powershellgallery.com/packages/Cohesity.PowerShell/1.7.2

Do reopen the ticket if the issue persist.
