### ISSUE TITLE
Add Physical Hosts to Backup Group

### ISSUE THREAD

**Issue by lorenzstorm1** [cohesity/cohesity-powershell-module#163]
## 📚 Documentation

Can you please add documentation on how to add a Physical Server to a Protection Group?
The Example for VMs doesn't work for Physical Servers:
Using this commands runs in error
$protectionjob = Get-CohesityProtectionJob -Id 162823
$protectionjob.sourceids = $protectionjob.sourceids + $ProtectionSource.protectionsource.id
$protectionJob | Set-CohesityProtectionJob -Confirm:$false

**Comment by bijayprasadtiwari** [comment]
ACK, will add sample/documentation and keep you updated.
