### ISSUE TITLE
Strange behaviour with Get-CohesityProtectionJob objects

### ISSUE THREAD

**Issue by kwongheng** [cohesity/cohesity-powershell-module#169]
## ❓ Questions and Requests

Hi,

I have writing some powershell health check scripts and trying to get status of project jobs

The objects returned shows that statuses alright, but I am not able to read those properties that was display, e.g. SLA. When I look at the member, I can see the full object properties instead. How can I just get those properties that are displayed, .e.g SLA, lastruntime instead of having to dig into all the properties and duplicate the work already done?

![thumbnail_image001 (1)_LI](https://user-images.githubusercontent.com/62384305/143835286-8a068aca-f9f4-4cc3-bd1a-8cf11a661f36.jpg)
![thumbnail_image002 (1)_LI](https://user-images.githubusercontent.com/62384305/143835299-39a6ccec-2f51-4441-8e41-7637b917193e.jpg)
![thumbnail_image003_LI](https://user-images.githubusercontent.com/62384305/143835307-5a5fe9c2-e6f5-4898-b56e-3d6975365c08.jpg)

**Comment by bijayprasadtiwari** [comment]
The cmdlets returns all the necessary information for a protection. You can get the desired results using the following,

 $jobs = Get-CohesityProtectionJob
$jobs[1].lastRun.backupRun.stats.startTimeUsecs
$jobs[1].lastRun.backupRun.slaViolated
$jobs[1].isPaused


![image](https://user-images.githubusercontent.com/43197022/144205822-f005dc10-b13c-4153-b25f-d60ac9761e31.png)

**Comment by bijayprasadtiwari** [comment]
@kwongheng , do let us know if that helps.

**Comment by kwongheng** [comment]
Thanks for the reply, my question is why is the output object with properties id,name,environment,lastruntime,sla.Ispaused not accessible as part of the returned objects? This behavour is strange, we don't expect to have to dive deep to grab those displayed columns

e.g.  $jobs = get-cohesityProtectionJob
I expect the following
$jobs[0].lastruntime --> output lastruntime as per table
$jobs[0].sla --> output "pass"

**Comment by bijayprasadtiwari** [comment]
@kwongheng , the properties id,name,environment,lastruntime,sla.Ispaused , should be accessible. The response from the cmdlet is converted to readable format and displayed to the user. 
The object hierarchy in the returned object is sent from the cohesity cluster, the powershell cmdlet does not alter the object, it simply relays the object from cohesity cluster to the user.

Request you to raise a ticket through proper channel if that does not solve the issue.

**Comment by kwongheng** [comment]
Thanks, in that case this is an issue, as you can see from my screeshot, I cannot access the returned objects properties from the cmdlet.

**Comment by pyashish** [comment]
Hi @kwongheng  looks like the values from backend are missing and there's nothing much our cmdlets can do , can you please ping support@cohesity.com. Please ref them this issue.

**Comment by kwongheng** [comment]
Sorry, I was very busy at work and now on vaca, I will get back to that when I get back to work. Still quite surprised to see cmdlets that doesn't follow powershell rules
