### ISSUE TITLE
Cohesity health check functions?

### ISSUE THREAD

**Issue by kwongheng** [cohesity/cohesity-powershell-module#170]
## 🚀 Feature Request

I am trying to develop a comprehensive health check for our cohesity cluster, however, I don’t find any direct functions to verify storage health or replication health or node health. Also I could not find any references as to what would constitute a comprehensive scripted daily health check of a pair of cohesity clusters.

**Comment by bijayprasadtiwari** [comment]
See if  Get-CohesityProtectionSourceSummary helps. 
Ref : https://cohesity.github.io/cohesity-powershell-module/#/cmdlets-reference/get-cohesityprotectionsourcesummary

**Comment by pyashish** [comment]
Hi @kwongheng  did the above cmdlet help you ?

**Comment by kwongheng** [comment]
Sorry, I was very busy and did not managed to visit this topic, I will need to check out, but what I was looking out for nodes and application health check. I guess looking at alerts and protectionjob is a good proxy for overall health.

**Comment by pyashish** [comment]
Closing this issue since no further requests have been raised.
