### ISSUE TITLE
Get-CohesityProtectionJob for Organization

### ISSUE THREAD

**Issue by burnziii** [cohesity/cohesity-powershell-module#174]
What is the correct syntax to list the protection jobs within a specified organization?
Get-CohesityProtectionJob only shows the protection jobs without any org.

Would be great if there are samples for multitenancy too.

Creating a user for every org is not possible due to restrictions.
Is there anyway to impersonate like within the UI?

**Comment by pyashish** [comment]
Hi @burnziii , currently we assume its a non-MT environment. For MT, you could use the tenant admin user . 

Impersonation is a privileged access for Admin and to be done via UI only. We will discuss this request but not planning to implement this in powershell anytime soon

**Comment by pyashish** [comment]
@KavishreeShanmugam11  can you take a look at this, along with MFA fix, we could probably add the support , if it already exists , enhance the documentation for the same .

**Comment by KavishreeShanmugam11** [comment]
Hi @burnziii , To login as a tenant use the user name should be in the format - LOCAL\user@tenant

**Comment by KavishreeShanmugam11** [comment]
It's already mentioned as one of the example in [Cohesity Powershell documentation](https://cohesity.github.io/cohesity-powershell-module/#/cmdlets-reference/connect-cohesitycluster)

**Comment by burnziii** [comment]
Great that worked with LOCAL\user@org.
Is there also any way to authenticate with MFA?

**Comment by KavishreeShanmugam11** [comment]
We are working on it, MFA will be a part of our next release.
