### ISSUE TITLE
Restore Oracle Database 

### ISSUE THREAD

**Issue by einarbey** [cohesity/cohesity-powershell-module#175]
## 🚀 Feature Request

Hi,

I don´t see any options to restore oracle database with powershell 

would be nice if you could add that feature to powershell as i would like to create script for oracle restore to alternate location

**Comment by pyashish** [comment]
We are looking at this request. @venmuthu  can you please a take a look ?

**Comment by naveena-maplelabs** [comment]
Please try with Restore-CohesityOracleDatabase cmdlet, support is added in 1.8.4 release
