### ISSUE TITLE
Get-CohesityViewDirectoryQuota fails to return all quotas

### ISSUE THREAD

**Issue by jl4509** [cohesity/cohesity-powershell-module#183]
On views with larger numbers of directory quotes, Get-CohesityViewDirectoryQuota fails to return all of the quotas.  When incomplete results are returned, the results include a cookie value.

It appears the rest API /public/viewDirectoryQuotas does pagination similiar to /public/viewUserQuotas.  Unfortunately this is not documented in the online Cohesity documentation.  Adding the returned cookie values to subsequent api calls allows retreiving all of the quotas.

**Comment by pyashish** [comment]
Ack , Thanks for bringing this to our notice, we'll update our documentation and put the commandlet pagination implementation in the backlog.

**Comment by KavishreeShanmugam11** [comment]
Latest powershell with the fix available at https://www.powershellgallery.com/packages/Cohesity.PowerShell/1.8.0
