### ISSUE TITLE
Get-CohesityAlert -MaxAlerts 10 fails

### ISSUE THREAD

**Issue by gerardiro** [cohesity/cohesity-powershell-module#185]
running the following command fails each time it is executed:

Get-CohesityAlert -MaxAlerts 10

PS D:\cohesity\Automation\WindowsAgent> Get-CohesityAlert -MaxAlerts 10
Get-CohesityAlert : Error converting value "kConfiguration" to type 'System.Nullable`1[Cohesity.Model.Alert+AlertCategoryEnum]'. Path '[0].alertCategory', 
line 1, position 173.
At line:1 char:1
+ Get-CohesityAlert -MaxAlerts 10
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-CohesityAlert], JsonSerializationException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonSerializationException,Cohesity.Powershell.Cmdlets.Cluster.GetCohesityAlert

Cohesity cluster is connected and running version 6.6d u1 with patchlevel 7

**Comment by KavishreeShanmugam11** [comment]
Latest powershell with the fix available at https://www.powershellgallery.com/packages/Cohesity.PowerShell/1.8.0
