### ISSUE TITLE
Can't access Properties in Arraylist of Find-CohesityObjectsForRestore

### ISSUE THREAD

**Issue by lorenzstorm1** [cohesity/cohesity-powershell-module#189]
## 🐛 Bug Report

Trying to do a MSSQL Restore of a random database. But I'm unable to access the arrays properties

## To Reproduce

(Write your steps here:)

1. $AllDBs = Find-CohesityObjectsForRestore -Environments KSQL
2. $AllDBs      

ObjectName                                                       Id   Environment ParentId JobName                JobId
----------                                                       --   ----------- -------- -------                -----
SQLEXPRESS/model                                                 3266 KSQL        3261     silver-mssql_09pm      10600
SQLEXPRESS/master                                                3268 KSQL        3261     silver-mssql_09pm      10600
SQLEXPRESS/SiteAudit                                             3267 KSQL        3261     silver-mssql_09pm      10600
MSSQLSERVER/model                                                6591 KSQL        6584     silver-mssqlnolog_11pm 516052
MSSQLSERVER/nextccdb                                             3400 KSQL        3393     silver-mssqlnolog_11pm 516052
ADREC/master                                                     3123 KSQL        3116     silver-mssqlnolog_11pm 516052
MSSQLSERVER/model                                                6525 KSQL        6519     silver-mssqlnolog_11pm 516052
VANTAGE/model                                                    3388 KSQL        3377     silver-mssqlnolog_11pm 516052
MSSQLSERVER/model                                                3005 KSQL        2999     silver-mssql_09pm      10600
MSSQLREPORTING/model                                             3011 KSQL        2999     silver-mssql_09pm      10600
MSSQLSERVER/ReportServerTempDB                                   3104 KSQL        3083     silver-mssql_09pm      10600
SRVCWEB_VP/M42Monitoring                                         3087 KSQL        3083     silver-mssql_09pm      10600
SRVCWEB_VP/M42WareHouse                                          3093 KSQL        3083     silver-mssql_09pm      10600
MSSQLSERVER/M42WareHouse                                         3101 KSQL        3083     silver-mssql_09pm      10600
MSSQLTEST/master                                                 2739 KSQL        2647     silver-mssql_09pm      10600
MSSQLTEST/msdb                                                   2749 KSQL        2647     silver-mssql_09pm      10600
MSSQLSERVER/P7S1QTMS                                             6853 KSQL        2647     silver-mssql_09pm      10600
MSSQLSERVER/VirtualManagerDB                                     2806 KSQL        2647     silver-mssql_09pm      10600
MSSQLTEST/sdmtest                                                2758 KSQL        2647     silver-mssql_09pm 
4. $AllDBs.id
No Output

## Expected behavior

4.  Should output all the Id's

## Actual Behavior

No Output

**Comment by lorenzstorm1** [comment]
found it: $AllDBs.SnapshottedSource.id

**Comment by pyashish** [comment]
Thanks @lorenzstorm1
