### ISSUE TITLE
The type name 'ServicePointManager' could not be found.

### ISSUE THREAD

**Issue by tl7689** [cohesity/cohesity-powershell-module#191]
Having inconsistent results when using Get-CohesityProtectionJobStatus or Get-CohesityProtectionJob

On the same system I would run through the command below in different powershell sessions in VScode, Powershell_ISE

import-module d:\cohesity.powershell.1.8.0\Cohesity.PowerShell.psd1

Connect to the cluster
connect-cohesitycluster -apikey {apikey} -server {server.domain.com}

start a protection job
start-cohesityprotectionjob -name {jobname}

get a list of protection job
get-cohesityprotectionjob

under the VScode session is where I started the job and that is where I can successfully execute all the functions and cmdlet while in the powershell_ise session that I stated after VScode, none of the functions that uses the invoke-restapi is successful.  they all return an error

Add-Type : ___\Temp\mkjjaxhf.0.cs(9) : The type name 'ServicePointManager' could not be found. This type has been forwarded to assembly 'System.Net.ServicePoint, Version=0.0.0.0, Culture=neutral, 
PublicKeyToken=cc7b13ffcd2ddd51'. Consider adding a reference to that assembly.
___\Temp\mkjjaxhf.0.cs(8) :         {
___\Temp\mkjjaxhf.0.cs(9) : >>>             ServicePointManager.ServerCertificateValidationCallback +=
___\Temp\mkjjaxhf.0.cs(10) :                 delegate
At___cohesity.powershell.1.8.0\Scripts\Utility\Enable-SelfSignedCertificates.ps1:7 char:5
+     Add-Type @"
+     ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
 
Add-Type : ___\Temp\mkjjaxhf.0.cs(14) : The type name 'X509Chain' could not be found. This type has been forwarded to assembly 'System.Security.Cryptography.X509Certificates, Version=0.0.0.0, Culture=neutral, 
PublicKeyToken=___'. Consider adding a reference to that assembly.
___\Temp\mkjjaxhf.0.cs(13) :                     X509Certificate certificate,
___\Temp\mkjjaxhf.0.cs(14) : >>>                     X509Chain chain,
___\Temp\mkjjaxhf.0.cs(15) :                     SslPolicyErrors errors
At___cohesity.powershell.1.8.0\Scripts\Utility\Enable-SelfSignedCertificates.ps1:7 char:5
+     Add-Type @"
+     ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
 
Add-Type : ___\Temp\mkjjaxhf.0.cs(15) : The type name 'SslPolicyErrors' could not be found. This type has been forwarded to assembly 'System.Net.Primitives, Version=0.0.0.0, Culture=neutral, 
PublicKeyToken=___'. Consider adding a reference to that assembly.
___\Temp\mkjjaxhf.0.cs(14) :                     X509Chain chain,
___\Temp\mkjjaxhf.0.cs(15) : >>>                     SslPolicyErrors errors
___\Temp\mkjjaxhf.0.cs(16) :                 )
At___cohesity.powershell.1.8.0\Scripts\Utility\Enable-SelfSignedCertificates.ps1:7 char:5
+     Add-Type @"
+     ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
 
Add-Type : Cannot add type. Compilation errors occurred.
At___cohesity.powershell.1.8.0\Scripts\Utility\Enable-SelfSignedCertificates.ps1:7 char:5
+     Add-Type @"
+     ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
    + FullyQualifiedErrorId : COMPILER_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand

**Comment by KavishreeShanmugam11** [comment]
Hi @tl7689 , May I know, what version of powershell you are trying and are you using powershell or powershell.core?

**Comment by tl7689** [comment]
It was powershell 5.1

**Comment by KavishreeShanmugam11** [comment]
Hi @tl7689 , What is the version of Cohesity.Powershell module that you are using ?

**Comment by tl7689** [comment]
> Hi @tl7689 , What is the version of Cohesity.Powershell module that you are using ?

I was using cohesity.powershell 1.8.0

**Comment by tl7689** [comment]
> Hi @tl7689, Tried to reproduce the issue in our setup with powershell version as 5.1.19041.1682 and Cohesity.Powershell module version 1.8.0. It's working fine in our setup.
> It looks like some environment issue.
> Can you please share the complete configuration of your setup (VSCode, powersehll ISE & windows version)?

I'm sorry, it's been awhile since  I posted so I do not remember which  version of vscode, as for the powershell ise, it's the version that comes with 5.1 and I'm running  windows 10 20h2.

Also I'm no longer working  on the project that would require  me to use this module so I don't think I would be able to reproduce it because  I no longer have access.
