### ISSUE TITLE
Get-CohesityProtectionSource inconsistent results on filtering Source Name.

### ISSUE THREAD

**Issue by DavidSeaton** [cohesity/cohesity-powershell-module#195]
## 🐛 Bug Report

Unable to provide a list of Source Names and have Get-CohesityProtectionSource provide the objects.

Should have some agility to search for Source Name.
(This is not a feature request, the process does not work.)

## To Reproduce

Perform the following:
1. Get-CohesityProtectionSource -Id 1348 --- Success
2. Get-CohesityProtectionSource -Id 1348 | ? {$_.name -eq "my.source.com"}  --- Success
3. Get-CohesityProtectionSource | ? {$_.name -eq "my.source.com"} --- FAIL

Inconsistent results even though object properties returned are Id, Name, etc.:
4. Get-CohesityProtectionSource -Environments KPhysical | Where-Object {$_.name -eq "my.source.com"}  --- Success
5. Get-CohesityProtectionSource -Environments KPhysical | Where-Object {$_.protectionsource.name -eq "my.source.com"} --- FAIL

## Expected behavior

Expected behavior is that providing or not providing ID should give me a list of objects to filter.

## Actual Behavior

This successfully works:
Get-CohesityProtectionSource |  Where-Object {$_.protectionsource.name -eq "my.source.com"}

## Suggested fix a Feature Request

Get-CohesityProtectionSource -Name my.source.com

**Comment by KavishreeShanmugam11** [comment]
ACK

**Comment by KavishreeShanmugam11** [comment]
Fixed this issue in v1.8.1 and is available in [powershell gallery](https://www.powershellgallery.com/packages/Cohesity.PowerShell/1.8.1) now.
