### ISSUE TITLE
When is 1.8.1 going to be built?

### ISSUE THREAD

**Issue by jason-carter-bzy** [cohesity/cohesity-powershell-module#197]
## ❓ Questions and Requests

We have had a fix identified with Get-CohesityProtectionSource back in May.  For us to move the API through our RTL I'd rather do it from an official release rather than the fix I was left with.  The code change is already in your repo just needs building.

**Comment by pyashish** [comment]
Sorry @jason-carter-bzy  , will try to prioritize this soon.

**Comment by KavishreeShanmugam11** [comment]
Hi @jason-carter-bzy , Sorry for the delay. 
v1.8.1 is published and is available in [powershell gallery](https://www.powershellgallery.com/packages/Cohesity.PowerShell/1.8.1) now.
