### ISSUE TITLE
Get-CohesityClusterConfiguration error

### ISSUE THREAD

**Issue by VirtuallyDan** [cohesity/cohesity-powershell-module#202]
## 🐛 Bug Report

When I run Get-CohesityClusterConfiguration, there is an error converting "SATA-SSD" to type "system.nullable" [Cohesity.Model.CountByTier+StorageTierEnum]

![image](https://user-images.githubusercontent.com/116685314/197884715-0dc3d2f6-3c66-4f93-b9c2-49b11c928b04.png)

The Cohesity node is a ROBO node running on HPE hardware.

## To Reproduce

1. Connect to cluster: **Connect-CohesityCluster -Server "my-cdp01" -Credential (Get-Credential -UserName "Admin" -Message "Enter Password for my-cdp01")**
2. Get cluster configuration: **$Config = Get-CohesityClusterConfiguration**
3. Error produced

## Expected behavior

$Config variable would have the configuration object so I can manipulate the objects and send it to Set-CohesityClusterConfiguration

## Actual Behavior

![image](https://user-images.githubusercontent.com/116685314/197885941-b6c3f08b-2e7b-4aba-9d64-431f6497edb6.png)

Get-CohesityClusterConfiguration: Error converting value "SATA-SSD" to type 'System.Nullable`1[Cohesity.Model.CountByTier+StorageTierEnum]'. Path 'diskCountByTier[0].storageTier', line 1, position 2050.

**Comment by KavishreeShanmugam11** [comment]
Hi @VirtuallyDan , this is due to the incorrect enum value specified in cohesity model for 'storageTier' field. Replaced the value with respect to the api response now. Fix will be available in next release (v1.8.2) sson.
Will file a bug to the api team ASAP.
