### ISSUE TITLE
Start-CohesityProtectionJob errors

### ISSUE THREAD

**Issue by jason-carter-bzy** [cohesity/cohesity-powershell-module#203]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

Backup of job fails to start

## To Reproduce

(Write your steps here:)

1.Start-CohesityProtectionJob -Name jobname -RunType KREGULAR -SourceIds sourceid
2.
3.

## Expected behavior

Backup would start.
Protection job was started successfully.

## Actual Behavior

Fell over with an unusual message.
Start-CohesityProtectionJob : Could not convert string to integer: kTo. Path '[104].alertingConfig.emailDeliveryTargets[0].recipientType', line 1, position 1383705.

![image](https://user-images.githubusercontent.com/76433676/198994470-19688f78-99a0-4f2c-a976-b5daa285d3f9.png)

**Comment by KavishreeShanmugam11** [comment]
Hi @jason-carter-bzy 
Will look into it, thanks for pointing it out.

**Comment by KavishreeShanmugam11** [comment]
Hi @jason-carter-bzy 
Cohesity Powershell module with the fix for above is issue is now avialbale in powershell gallery,

[PowerShell Gallery | Cohesity.PowerShell 1.8.3](https://www.powershellgallery.com/packages/Cohesity.PowerShell/1.8.3)
