### ISSUE TITLE
Get-CohesityMSSQLObject fails when throttling was modified for a source

### ISSUE THREAD

**Issue by thierryvandurme** [cohesity/cohesity-powershell-module#207]
Get-CohesityMSSQLObject: Could not convert string to integer: kNoThrottling. Path '[23].applicationServer.registrationInfo.physicalParams.throttlingConfig.networkThrottlingConfig.patternType', line 1, position 833846.

**Comment by naveena-maplelabs** [comment]
The yaml file is incorrect, Created ticket to track the same.
ENG-338175

**Comment by KavishreeShanmugam11** [comment]
Fixed
