### ISSUE TITLE
Please add the ability to set/edit the Logical Quota/Alert with Set-CohesityView

### ISSUE THREAD

**Issue by KuJoe** [cohesity/cohesity-powershell-module#208]
## 🚀 Feature Request

Similar to issue #30, please add these parameters to the Set-CohesityView command to allow us to set or edit the Logical Quota and Alert Threshold. Thank you.

**Comment by naveena-maplelabs** [comment]
You can follow the steps to update the quota policy of a view
```
>$quotaPolicy = [Cohesity.Model.QuotaPolicy]::new()
>$view = Get-CohesityView
>$view.LogicalQuota = $quotaPolicy
>$view | Set-CohesityView
```
