### ISSUE TITLE
Please allow "Overwrite Existing VM" for Restore-CohesityVMwareVM command.

### ISSUE THREAD

**Issue by KuJoe** [cohesity/cohesity-powershell-module#212]
## 🚀 Feature Request

Please add a flag to allow overwriting existing VMs like in the GUI (Existing VM Handling) so that we can restore a VM via Powershell using the Restore-CohesityVMwareVM command without having to delete it in VMware first.

## Example or reference 

Maybe something like **-Overwrite** so it'd look like this: 
`Restore-CohesityVMwareVM -TaskName "Test-Restore" -SourceId 2 -JobId 8 -Overwrite -DisableNetwork -PoweredOn`

**Comment by naveena-maplelabs** [comment]
Code changes are pushed to repo, will be available in the next release.
