### ISSUE TITLE
New-CohesityProtectionJob - A parameter cannot be found that matches parameter name 'AlertOn'

### ISSUE THREAD

**Issue by bbolip** [cohesity/cohesity-powershell-module#217]
I try to create a Protection Job for type kSQL. When I want to assign  AlertOn and EmailAddress I get following error:
`New-CohesityProtectionJob : A parameter cannot be found that matches parameter name 'AlertOn'.`

This is the command:
`New-CohesityProtectionJob -Name $protectionJobName -PolicyName $policyName -Environment kSQL -ParentSourceId $sourceId -SourceId $sourceId -StorageDomainName "DefaultStorageDomain" -ScheduleStartTime "01/01/2023 03:00:00 AM" -AlertOn KFailure -EmailAddress $altertEmailAddresses`

Description of the command _[New-CohesityProtectionJob](https://cohesity.github.io/cohesity-powershell-module/#/cmdlets-reference/new-cohesityprotectionjob?id=new-cohesityprotectionjob)_ says it should be possible to use those parameters.
I am using module version 1.8.4.

See PowerShell Outcome below:
![cohesity_powershell](https://user-images.githubusercontent.com/126671601/226952756-01163b0c-0f85-4ff1-8b5e-2cd8cfa10546.png)

**Comment by pyashish** [comment]
@bbolip , which cluster version did you try this on ?

**Comment by naveena-maplelabs** [comment]
![image](https://user-images.githubusercontent.com/62049303/229107430-68f20e49-73c8-4105-ae60-7421816fa650.png)
@bbolip We couldn't reproduce the issue, are you still facing this issue.
Is the job creation with email address working for other environments. For MsSql job creation you can refer the sample available [here](https://github.com/cohesity/cohesity-powershell-module/blob/master/samples/ProtectionJob/CreateMSSQLJob.ps1).
