### ISSUE TITLE
New-CohesityProtectionJob - How to create Protection Job for SQL with SqlSpecialParameters (environmentParameters))

### ISSUE THREAD

**Issue by bbolip** [cohesity/cohesity-powershell-module#218]
## ❓ Questions and Requests

I want to create a protection job for SQL with special MS SQL Settings. Therefore I would use the command [New-CohesityProtectionJob](https://cohesity.github.io/cohesity-powershell-module/#/cmdlets-reference/new-cohesityprotectionjob?id=new-cohesityprotectionjob).
To define the MS SQL Settings I would assume I have to set this in parameter [SourceSpecialParameters](https://cohesity.github.io/cohesity-powershell-module/#/cmdlets-reference/new-cohesityprotectionjob?id=-sourcespecialparameters).

I want to create the job with following parameters (Example from existing job):
![cohesity_powershell3](https://user-images.githubusercontent.com/126671601/226957340-1d7fc9c9-2d55-4787-ab75-4c021490817a.png)

I found some other scripts where a special parameter from type _[Cohesity.Model.SourceSpecialParameter]_ needs to be defined:
`$SourceSpecialParameter = [Cohesity.Model.SourceSpecialParameter]::new()`
![cohesity_powershell2](https://user-images.githubusercontent.com/126671601/226956559-086d1c3c-965b-4190-8469-d3b53b88be35.png)

Then I think I have to set the _[SqlSpecialParameters](https://github.com/cohesity/cohesity-powershell-module/blob/e6df890c747a19ab4805fcc3bfd9e2e54223c5f4/src/Cohesity.Powershell.Models/SourceSpecialParameter.cs)_:
`$SourceSpecialParameter.SqlSpecialParameters = [Cohesity.Model.SqlSpecialParameters]::new()`

But I get this error:
`Unable to find type [Cohesity.Model.SqlSpecialParameters].`

For example OracleSpecialParameters works fine:
`$SourceSpecialParameter.OracleSpecialParameters = [Cohesity.Model.OracleSpecialParameters]::new()`

**Comment by naveena-maplelabs** [comment]
Please find the following code for Sql paramaeters support
```
$environmentParams = [Cohesity.Model.EnvironmentTypeJobParameters]::new()
$sqlParameters = [Cohesity.Model.SqlEnvJobParameters]::new()
$sqlParameters.userDatabasePreference = "kBackupAllDatabases"
$sqlParameters.numStreams = 1
$sqlParameters.backupSystemDatabases = $true
$sqlParameters.backupType = "kSqlNative"
$sqlParameters.withClause = ""
$sqlParameters.isCopyOnlyFull = $true
$sqlParameters.aagPreference = "kPrimaryReplicaOnly"
$sqlParameters.backupType = "kSqlVSSVolume"
$environmentParams.sqlParameters = $sqlParameters
$protectionJobObject.environmentParameters = $environmentParams
```
