### ISSUE TITLE
Problem with plus in names

### ISSUE THREAD

**Issue by MSpeck74** [cohesity/cohesity-powershell-module#226]
PS C:\Windows\system32> (Get-CohesityProtectionJob).Name
PG VMware VMs default
PG NAS BLCo+Groups+Personal
PG NAS TAblage+Witnesses
PG NAS Applications
PG NAS UserHomes
PG M365 Mailbox
PG M365 Teams
PG M365 SharePoint
PG M365 OneDrive
PG SQL JUG-SQL-x3
PG SQL JUG-SQL-99
PG SQL FV-Gartenfrisch
PG SQL JUG-SQL-x4
PG Active Directory
MM Test
PG Exchange
PS C:\Windows\system32> Get-CohesityProtectionJob -Names (Get-CohesityProtectionJob).Name

Id    Name                   Environment     LastRunTime         SLA  IsPaused
--    ----                   -----------     -----------         ---  --------
2148  PG NAS Applications    kGenericNas     10.07.2023 13:01:18 Pass False
2276  PG M365 Mailbox        kO365Exchange   09.07.2023 23:05:01 Pass False
2280  PG M365 Teams          kO365Teams      10.07.2023 00:05:04 Pass False
2281  PG M365 SharePoint     kO365Sharepoint 10.07.2023 01:05:04 Pass False
2285  PG M365 OneDrive       kO365OneDrive   10.07.2023 02:05:02 Pass False
3464  PG SQL JUG-SQL-x3      kSQL            10.07.2023 10:10:34 Pass False
3476  PG SQL JUG-SQL-99      kSQL            10.07.2023 02:05:02 Pass False
4919  PG SQL FV-Gartenfrisch kSQL            09.07.2023 14:00:03 Pass False
5624  PG SQL JUG-SQL-x4      kSQL            09.07.2023 21:05:03 Pass False
16383 PG Active Directory    kAD             10.07.2023 12:57:56 Pass False
23018 MM Test                kO365Exchange                       Pass True
49331 PG Exchange            kExchange       10.07.2023 04:05:02 Pass False

-----------------------

PS C:\Windows\system32> Get-CohesityProtectionJob

Id    Name                             Environment     LastRunTime         SLA  IsPaused
--    ----                             -----------     -----------         ---  --------
[...]
2083  PG NAS BLCo+Groups+Personal      kGenericNas     10.07.2023 13:01:18 Pass False
[...]

PS C:\Windows\system32> Get-CohesityProtectionJob -Ids 2083

Id   Name                        Environment LastRunTime         SLA  IsPaused
--   ----                        ----------- -----------         ---  --------
2083 PG NAS BLCo+Groups+Personal kGenericNas 10.07.2023 13:01:18 Pass False

PS C:\Windows\system32> (Get-CohesityProtectionJob -Ids 2083).Name
PG NAS BLCo+Groups+Personal
PS C:\Windows\system32> Get-CohesityProtectionJob -Names (Get-CohesityProtectionJob -Ids 2083).Name
PS C:\Windows\system32>

Renamed:
PS C:\Windows\system32> Get-CohesityProtectionJob

Id    Name                             Environment     LastRunTime         SLA  IsPaused
--    ----                             -----------     -----------         ---  --------
[...]
2083  PG NAS BLCo_Groups_Personal      kGenericNas     10.07.2023 14:01:20 Pass False
[...]

PS C:\Windows\system32> Get-CohesityProtectionJob -Ids 2083

Id   Name                        Environment LastRunTime         SLA  IsPaused
--   ----                        ----------- -----------         ---  --------
2083 PG NAS BLCo_Groups_Personal kGenericNas 10.07.2023 14:01:20 Pass False

PS C:\Windows\system32> (Get-CohesityProtectionJob -Ids 2083).Name
PG NAS BLCo_Groups_Personal
PS C:\Windows\system32> Get-CohesityProtectionJob -Names (Get-CohesityProtectionJob -Ids 2083).Name

Id   Name                        Environment LastRunTime         SLA  IsPaused
--   ----                        ----------- -----------         ---  --------
2083 PG NAS BLCo_Groups_Personal kGenericNas 10.07.2023 14:01:20 Pass False

PS C:\Windows\system32>

**Comment by KavishreeShanmugam11** [comment]
This issue happens due to special character in job name, which used for constructing protection job url.

**Comment by KavishreeShanmugam11** [comment]
Issue resolved.
https://www.powershellgallery.com/packages/Cohesity.PowerShell/1.9.3
https://www.powershellgallery.com/packages/Cohesity.PowerShell.Core/1.9.3
