### ISSUE TITLE
Cannot use -id on Get-CohesityProtectionSource or Get-CohesityProtectionSourceObject

### ISSUE THREAD

**Issue by anddom1** [cohesity/cohesity-powershell-module#23]
When trying to use the Get-CohesityProtectionSource and Get-CohesityProtectionSourceObject using the -id get an error. I am testing on cluster version 6.0.1a:
PS M:\> Get-CohesityProtectionSource -Id 4329
Get-CohesityProtectionSource : The requested entity could not be found
At line:1 char:1
Get-CohesityProtectionSource -Id 4329

But the ID is present:
PS C:\> Get-CohesityProtectionSource -Environments kSQL
Id      Name                   Environment  RefreshedTime       
790   phsqldagtest1      kVMware       9/12/2018 8:21:43 AM
781   phsqldagtest2      kVMware       9/12/2018 8:24:27 AM
712   phoamagtestnew kVMware       9/12/2018 8:21:50 AM
4329 phesscmsqltst1    kVMware       9/12/2018 8:25:40 AM

**Comment by WaywardScripts** [comment]
The problem here is that GetCohesityProtectionSource attempts to find root nodes with the given ID, and then search through the children for the same matching ID. It will only ever return the root nodes.

**Comment by sagnihotri-cohesity** [comment]
Thanks for reporting this. The fix for this will be included in the next update on PowerShell Gallery.

**Comment by sagnihotri-cohesity** [comment]
Fix included in v1.0.4. https://www.powershellgallery.com/packages?q=cohesity
