### ISSUE TITLE
Return active and queued copy tasks 

### ISSUE THREAD

**Issue by bradbaughn** [cohesity/cohesity-powershell-module#27]
Would be valuable to be able to see an output of all active and queued copy tasks with copy tasks progress and time remaining. Also, having the queued jobs listed in the order that they will run would be helpful as well.

**Comment by bijayprasadtiwari** [comment]
Fixed in release v1.1.1
https://github.com/cohesity/cohesity-powershell-module/releases/tag/v1.1.1

**Comment by ashish-cohesity** [comment]
Closing as per @bijayprasadtiwari 's comments
