### ISSUE TITLE
Requesting ability to set quota logical quota and alert quota on view

### ISSUE THREAD

**Issue by irrision** [cohesity/cohesity-powershell-module#30]
I don't see this as a documented feature of the: New-CohesityView or Set-CohesityView commandlets but it would be very handy for scripting the creation of user facing views that require a quota applied and it appears all other view functionality already exists in this commandlet.

**Comment by sagnihotri-cohesity** [comment]
Added -LogicalQuotaInBytes and -AlertQuotaInBytes parameters to [New-CohesityView](https://cohesity.github.io/cohesity-powershell-module/#/cmdlets-reference/new-cohesityview) in v1.0.8.
