### ISSUE TITLE
Sub Share Creation with ACLs

### ISSUE THREAD

**Issue by bradbaughn** [cohesity/cohesity-powershell-module#33]
Requesting the ability to create sub shares.  With proper ACLs would be ideal, but at the least the ability to create sub shares within a View would be helpful for migrations

**Comment by sagnihotri-cohesity** [comment]
Added [Add-CohesityViewShare](https://cohesity.github.io/cohesity-powershell-module/#/cmdlets-reference/add-cohesityviewshare) for this in v1.0.8.
