### ISSUE TITLE
Unable to run Find-CohesityFilesForRestore in Windows Powershell

### ISSUE THREAD

**Issue by ghost** [cohesity/cohesity-powershell-module#37]
Instantly errors out with:

Find-CohesityFilesForRestore : runtime error: invalid memory address or nil pointer dereference. 
 Stack trace: goroutine 240953 [running]:
cohesity/util/utils/misc.GetRuntimeStackTrace(0x1000, 0xc423ec7c00, 0x40, 0xc424301298)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/util/utils/misc/misc.go:247 +0x75
cohesity/iris/server/services/web/interceptors.PanicHandler.func1.1(0xc422ba2a00, 0x7f77f01e1938, 0xc4242f2380)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/web/interceptors/interceptors.go:176 +0x149
panic(0x10fd080, 0xc4200100c0)
	/home/cohesity/software/toolchain/x86_64-linux/go-1.7/src/runtime/panic.go:458 +0x243
cohesity/iris/server/assemblers/converters.ConvertFileSearchResult(0xc42096d480, 0x0)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/assemblers/converters/restore_task_converter.go:963 +0x135
cohesity/iris/server/assemblers/converters.(*ApiDataConverter).ConvertFileResults(0xc4228e1b68, 0xc42060c100, 0x0)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/assemblers/converters/restore_task_converter.go:984 +0xe3
cohesity/iris/server/ops/public/restore.(*SearchRestoredFilesOp).PostExecute(0xc4237dfec0, 0x0)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/ops/public/restore/search_restored_files_op.go:56 +0x5b
cohesity/iris/server/baseops.ExecuteYodaReadOp(0x1a53be0, 0xc4237dfec0, 0xc423f59080)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/baseops/yoda_base_op.go:39 +0x71
cohesity/iris/server/services/rest/public.SearchRestoredFiles(0xc4204a8b00, 0xc422ba2a00, 0xc425c17530, 0x7f77f01e1938, 0xc4242f2380, 0xc423e26960, 0x1)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/rest/public/restore_controller.go:390 +0xe1
cohesity/iris/server/services/rest/base.(*RestHandler).WrapperHandler(0xc4200bd2c0, 0xc4204a8b00, 0xc422ba2a00, 0xc425c17530, 0x7f77f01e1938, 0xc4242f2380, 0xc423e26960)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/rest/base/base_rest_handler.go:197 +0x247
cohesity/iris/server/services/rest/base.(*RestHandler).WrapperHandler-fm(0xc4204a8b00, 0xc422ba2a00, 0xc425c17530, 0x7f77f01e1938, 0xc4242f2380, 0xc423e26960)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/web/webserver.go:185 +0x66
reflect.Value.call(0x10f7f80, 0xc420965b90, 0x13, 0x1305021, 0x4, 0xc423342500, 0x5, 0x5, 0x18, 0x10f7f80, ...)
	/home/cohesity/software/toolchain/x86_64-linux/go-1.7/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x10f7f80, 0xc420965b90, 0x13, 0xc423342500, 0x5, 0x5, 0xc42048f800, 0xc42129cb40, 0x670000c424301c80)
	/home/cohesity/software/toolchain/x86_64-linux/go-1.7/src/reflect/value.go:302 +0xa4
github.com/codegangsta/inject.(*injector).Invoke(0xc422c28c80, 0x10f7f80, 0xc420965b90, 0xd56a67, 0x10e1c60, 0xc42161d590, 0xc424301c68, 0xc424301c78)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/build/gobuild/toolchainlibs/go-inject/src/github.com/codegangsta/inject/inject.go:102 +0x335
github.com/go-martini/martini.(*context).Invoke(0xc421d14690, 0x10f7f80, 0xc420965b90, 0x16, 0xc424301cd8, 0xa1c8b5, 0xc422c28c80, 0x1227100)
	<autogenerated>:29 +0x61
github.com/go-martini/martini.(*routeContext).run(0xc425c17560)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/build/gobuild/toolchainlibs/go-martini/src/github.com/go-martini/martini/router.go:350 +0x71
github.com/go-martini/martini.(*route).Handle(0xc42052c640, 0x7f77f01e1970, 0xc421d14690, 0x7f77f01e1938, 0xc4242f2380)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/build/gobuild/toolchainlibs/go-martini/src/github.com/go-martini/martini/router.go:229 +0x10f
github.com/go-martini/martini.(*router).Handle(0xc42096aa50, 0x7f77f01e1938, 0xc4242f2380, 0xc423e26960, 0x7f77f01e1970, 0xc421d14690)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/build/gobuild/toolchainlibs/go-martini/src/github.com/go-martini/martini/router.go:112 +0x2af
gith
At line:1 char:1
+ Find-CohesityFilesForRestore
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Find-CohesityFilesForRestore], Exception
    + FullyQualifiedErrorId : System.Exception,Cohesity.Powershell.Cmdlets.Recovery.FindCohesityFilesForRestore

**Comment by sagnihotri-cohesity** [comment]
@br3adman21  This was a regression in Cohesity version 6.1, upgrading to Cohesity version 6.1.1 should fix the issue.
