### ISSUE TITLE
 Get-CohesityProtectionJobRun

### ISSUE THREAD

**Issue by abashir236** [cohesity/cohesity-powershell-module#38]
Need ability to query cohesity protection jobs that were run and filter by those with a status of  "kFailure".

**Comment by bseltz-cohesity** [comment]
Get-CohesityProtectionJobRun | Where-Object { $_.BackupRun.Status -eq 'kFailure' }

**Comment by abashir236** [comment]
Perfect!! Hey sorry but last question, how can I filter for date? I tried to convert to unix timestamp but couldn’t get it to work.

**Comment by bseltz-cohesity** [comment]
Here's how to get just the past 24 hours: 

Get-CohesityProtectionJobRun -StartTime (Convert-CohesityDateTimeToUsecs -DateTime ((get-date).AddHours(-24)))  | Where-Object { $_.BackupRun.Status -eq 'kFailure' }

**Comment by abashir236** [comment]
Work! Thanks a lot sir.
