### ISSUE TITLE
Backup Report

### ISSUE THREAD

**Issue by abashir236** [cohesity/cohesity-powershell-module#39]
Hey,

Trying to output the report of backups for a specified time frame such as on the Cohesity GUI. I did not see any commands for reporting thus far. Any help is appreciated.

thanks.

**Comment by bseltz-cohesity** [comment]
How about...

```
$daysAgoStart = 3
$daysAgoEnd = 2
Get-CohesityProtectionJobRun -StartTime (Convert-CohesityDateTimeToUsecs -DateTime (Get-Date).AddDays(-$daysAgoStart)) -EndTime (Convert-CohesityDateTimeToUsecs -DateTime (Get-Date).AddDays(-$daysAgoEnd))
```

**Comment by abashir236** [comment]
Thanks sir i appreciate. But you helped me with this yesterday and what i am asking today is how to generate just a report word for word like the gui since the gui lists by source objects and not by job name. Job name is not really telling as there could be multiple source objects within one job name. If I stand corrected then please do advise. And thanks a lot in advance sir.

**Comment by bseltz-cohesity** [comment]
Ah I see. Let me work on that. In the mean time, see if this gives you what you want: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/recoveryPoints

**Comment by bseltz-cohesity** [comment]
```$runs = Get-CohesityProtectionJobRun -StartTime (Convert-CohesityDateTimeToUsecs -DateTime (Get-Date).AddDays(-1))
foreach($run in $runs){
    $run
    $run.backupRun.SourceBackupStatus | foreach-object {
        "`t$($_.Status)`t$($_.Source.Name)"
    }
}
```

**Comment by abashir236** [comment]
It doesnt match the gui information still. Looks like it even lists source objects that did not fail.

**Comment by abashir236** [comment]
Hey sir, would you happen to have any hints on where to go from here. Shall i open a ticket with cohesity?

**Comment by bseltz-cohesity** [comment]
How about this...
```
. ./cohesity-api.ps1
apiauth mycluster admin
api get reports/protectionSourcesJobsSummary?outputFormat=csv | Out-File report.csv
```

**Comment by abashir236** [comment]
im not sure exactly how to run this.

**Comment by bseltz-cohesity** [comment]
https://github.com/bseltz-cohesity/scripts/tree/master/powershell/summaryReport

**Comment by abashir236** [comment]
Ran into the following errors when i ran your script sir:

The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation

The '<' operator is reserved for future use.

Missing file specification after redirection operator.

**Comment by bseltz-cohesity** [comment]
Please provide the command line that you entered. There are no & nor < in the script at all.

**Comment by abashir236** [comment]
.\summaryReport.ps1 -vip <ip> -username <user_name> -domain <domain>

After going to directory where i saved the 2 scripts summaryReport.ps1 and cohesity-api.ps1 i typed the command above

**Comment by abashir236** [comment]
of course after -vip is the ipaddress of the node

**Comment by bseltz-cohesity** [comment]
Sorry it's not clear from what you provided. Can you confirm that your command line looks like this:
```
.\summaryReport.ps1 -vip mycluster.mydomain.net -username myuser -domain mydomain.net
```

**Comment by abashir236** [comment]
So are you saying that I cannot use the ip of one of the cohesity nodes as the argument for -vip

**Comment by bseltz-cohesity** [comment]
IP address is fine for the -vip argument.

**Comment by abashir236** [comment]
Then that is the only thing that’s different from my command and yours...now do i have to include domain name along with ip?

**Comment by bseltz-cohesity** [comment]
Here's an example command line using IP for -vip: 
```
.\summaryReport.ps1 -vip 192.168.1.198 -username myuser -domain mydomain.net
```

**Comment by abashir236** [comment]
Then I followed that exactly but got those errors. Btw when I looked in the summaryReport.ps1 file I actually saw some ampersands

**Comment by bseltz-cohesity** [comment]
Did you use the download instructions provided in the resume? It sounds like your files are corrupt which will happen if you don't use the download commands

**Comment by abashir236** [comment]
Ahh I didn’t realize that I had to use that since there’s other instructions about manual downloading

**Comment by abashir236** [comment]
case: 00076809

**Comment by abashir236** [comment]
Case: 00076809

**Comment by abashir236** [comment]
> Can you please open a Cohesity support case, so that we can get on a conference call. Thanks

00076809

**Comment by abashir236** [comment]
Case opened
