### ISSUE TITLE
Register-CohesityProtectionSourcePhysical

### ISSUE THREAD

**Issue by komorek88** [cohesity/cohesity-powershell-module#41]
Trying to Create a script for it.

I cannot make command to work.

When I try to register server : 
Register-CohesityProtectionSourcePhysical -server server_name -HostType KWindows -PhysicalType KHost

I do receive error:

Register-CohesityProtectionSourcePhysical : runtime error: invalid memory address or nil pointer dereference. 
 Stack trace: goroutine 77849 [running]:
cohesity/util/utils/misc.GetRuntimeStackTrace(0x1000, 0xc42833a200, 0x40, 0xc42665b160)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/util/utils/misc/misc.go:249 +0x75
cohesity/iris/server/services/web/interceptors.PanicHandler.func1.1(0xc423347680, 0x7f80111aa588, 0xc429741980)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/web/interceptors/interceptors.go:176 +0x149
panic(0x11fd740, 0xc4200100d0)
	/home/cohesity/software/toolchain/x86_64-linux/go-1.7/src/runtime/panic.go:458 +0x243
cohesity/iris/server/assemblers/converters.ConvertRegisterProtectionSourceParameters(0xc426ebba70, 0xc42108a720)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/assemblers/converters/protection_source_converter.go:1932 +0x1d5
cohesity/iris/server/ops/public/protectionSource.NewRegisterProtectionSourceOp(0xc420421000, 0xc423347680, 0xc426ebba70, 0xc4228283c0)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/ops/public/protectionSource/register_protection_source_op.go:54 +0xa2
cohesity/iris/server/services/rest/public.RegisterProtectionSource(0xc420421000, 0xc423347680, 0xc4281f6f00, 0x7f80111aa588, 0xc429741980, 0xc4228283c0, 0x1071201)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/rest/public/protection_source_controller.go:536 +0xbe
cohesity/iris/server/services/rest/base.(*RestHandler).WrapperHandler(0xc42033cdc0, 0xc420421000, 0xc423347680, 0xc4281f6f00, 0x7f80111aa588, 0xc429741980, 0xc4228283c0)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/rest/base/base_rest_handler.go:197 +0x2a2
cohesity/iris/server/services/rest/base.(*RestHandler).WrapperHandler-fm(0xc420421000, 0xc423347680, 0xc4281f6f00, 0x7f80111aa588, 0xc429741980, 0xc4228283c0)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/web/webserver.go:185 +0x66
reflect.Value.call(0x11f8340, 0xc42058b2f0, 0x13, 0x142379d, 0x4, 0xc421ae5400, 0x5, 0x5, 0x18, 0x11f8340, ...)
	/home/cohesity/software/toolchain/x86_64-linux/go-1.7/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x11f8340, 0xc42058b2f0, 0x13, 0xc421ae5400, 0x5, 0x5, 0xc4200b4c00, 0xc42208e000, 0xec00000000000002)
	/home/cohesity/software/toolchain/x86_64-linux/go-1.7/src/reflect/value.go:302 +0xa4
github.com/codegangsta/inject.(*injector).Invoke(0xc420e7af20, 0x11f8340, 0xc42058b2f0, 0xde7ad7, 0x11e12a0, 0xc4281f6540, 0xc42665bb30, 0xc42665bb40)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/build/gobuild/toolchainlibs/go-inject/src/github.com/codegangsta/inject/inject.go:102 +0x335
github.com/go-martini/martini.(*context).Invoke(0xc4295a1bd0, 0x11f8340, 0xc42058b2f0, 0x16, 0xc42665bba0, 0xa95305, 0xc420e7af20, 0x13367e0)
	<autogenerated>:29 +0x61
github.com/go-martini/martini.(*routeContext).run(0xc4281f6f30)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/build/gobuild/toolchainlibs/go-martini/src/github.com/go-martini/martini/router.go:350 +0x71
github.com/go-martini/martini.(*route).Handle(0xc420963d60, 0x7f80111aa5c0, 0xc4295a1bd0, 0x7f80111aa588, 0xc429741980)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/build/gobuild/toolchainlibs/go-martini/src/github.com/go-martini/martini/router.go:229 +0x10f
github.com/go-martini/martini.(*router).Handle(0xc420f1e230, 0x7f80111aa588, 0xc429741980, 0xc4228283c0, 0x7f80111aa5c0, 0xc4295a1bd0)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/build/gobuild/toolchainlibs/go-martini/src/github.com/go-martini/martini/router.go:112 +0x2af
github.com/go-martini/martini.(Router).Handle-fm(0x7f80111aa588, 0xc429741980, 0xc4228283c0, 0x7f80111aa5c0, 0xc4295a1bd0)
	/mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/web/webserver.go:1160 +0x61
reflect.Value.call(0x11bb780, 0xc420f34420, 0x13, 0x142379d, 0x4, 0xc423392690, 0x3, 0x3, 0xc42665c100, 0x11bb780, ...)
At line:1 char:1
+ Register-CohesityProtectionSourcePhysical -server server_name  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Register-Cohesi...nSourcePhysical], Exception
    + FullyQualifiedErrorId : System.Exception,Cohesity.Powershell.Cmdlets.ProtectionSource.RegisterCohesityProtectionSourcePhysical

FYI - in server_name field is actual server name on my side.

I did check and from the UI I can register this server.

I did try via ip or other server and received same error

**Comment by sagnihotri-cohesity** [comment]
@komorek88 This is a bug in the API and a fix is available which will need to be applied on the Cohesity Cluster. Please open a support ticket and mention FI-4227. The fix is included in the subsequent Cohesity versions.

**Comment by komorek88** [comment]
Thanks for that support is working on it.

**Comment by sagnihotri-cohesity** [comment]
Closing this as this will be resolved by the support ticket.
