### ISSUE TITLE
Register-CohesityProtectionSourceMSSQL

### ISSUE THREAD

**Issue by komorek88** [cohesity/cohesity-powershell-module#44]
I am trying to create script witch will first register with agent servers from a file.
Then will register those as SQL.

While I managed to register all with register all with one click as physical source.
I cannot do the same with SQL.

Option 1 how I could do it : 
- I could use Register-CohesityProtectionSourceMSSQL and register with use of actual name not ID (although this is not supported)

Option 2 : 

- I could use get_cohesityprotectionsource to get ID and use Where to limit objects although either Name and ID is not actual property so I cannot use where or select on those properties

Any ideas?

**Comment by bseltz-cohesity** [comment]
The name and id properties are within the ProtectionSource property. So for example:

$id = (Get-CohesityProtectionSource | Where-Object { $_.ProtectionSource.Name -eq 'myserver.mydomain.net' }).ProtectionSource.id

**Comment by komorek88** [comment]
Thank you Also just realize Get-CohesityProtectionSourceObject will resolve my problem :) thank you !

**Comment by sagnihotri-cohesity** [comment]
Closing.
