### ISSUE TITLE
How do I get DatastoreId and ResourcePoolId from ProtectionSourceObject

### ISSUE THREAD

**Issue by viciousvex** [cohesity/cohesity-powershell-module#45]
I want to restore a backed up VM to a new location where -ResourcePoolId, VMFolderId and -DatastoreId are unknown or subject to change. Is there a way I can get these Ids of the target vCenter?

**Comment by sagnihotri-cohesity** [comment]
@viciousvex You can get the Ids of target ResourcePool or Datastore as below:
`Get-CohesityProtectionSourceObject | Where-Object { $_.VmWareProtectionSource.Type -match "kResourcePool" -and $_.VmWareProtectionSource.Name -match "Demo" }`

The above example only returns resourcepools that match the name "Demo"

**Comment by sagnihotri-cohesity** [comment]
@viciousvex  In case of datastores, please use `-IncludeDatastores` switch as below:
`Get-CohesityProtectionSourceObject -IncludeDatastores | Where-Object { $_.VmWareProtectionSource.Type -match "kDatastore" -and $_.VmWareProtectionSource.Name -match "test-datastore" }`

**Comment by viciousvex** [comment]
Ah! Very nice. Thanks for your help and great work with the PowerShell API.
