### ISSUE TITLE
Copy-CohesityMSSQLObject

### ISSUE THREAD

**Issue by komoreka** [cohesity/cohesity-powershell-module#48]
Hi I am trying to use powershell to clone here are my data used : 
-taskname "sql-clone-task1" = random name
-sourceid 2248 = Get-CohesityMSSQLObject then from particular DB object "ID"
-hostsourceid 2234 = Get-CohesityMSSQLObject then from particular DB object "parentID"
-JobId 5456 = Get-CohesityProtectionJob then from particular job which i want to clone from object "ID"
-NewDatabaseName "ClonedTest" = random name
-InstanceName "MSSQLSERVER" = instance name got from actual name
-TargetHostId 1515 = Get-CohesityMSSQLObject (again parentid of destinated host

Copy-CohesityMSSQLObject -TaskName "sql-clone-task1" -SourceId 2248 -HostSourceId 2234 -JobId 5456 -NewDatabaseName "ClonedTest" -InstanceName "MSSQLSERVER" -TargetHostId 1515

Error I receive is : 

opy-CohesityMSSQLObject : Could not find an appropriate full backup for the requested point in time(-1) for db [type: kSQL, entity_id: 2248, MSSQLSERVER/name-db
At line:1 char:1
+ Copy-CohesityMSSQLObject -TaskName "sql-clone-task1" -SourceId 2248 - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-CohesityMSSQLObject], Exception
    + FullyQualifiedErrorId : System.Exception,Cohesity.Powershell.Cmdlets.Clone.CopyCohesityMSSQLObject

results for : 

Get-CohesityProtectionJobRun -JobId 5456

Id     Start Time          RunType  JobId JobName                          Environment Status   SnapshotsDeleted Expiry Time        
--     ----------          -------  ----- -------                          

Not sure whats wrong here

**Comment by bijayprasadtiwari** [comment]
Fixed the bug in commit : 8e9578cff0d4ae0d7c7493206bf78ee032a0e167
The fix will be available in next release.
The start time need to be provided for the operation.
In the fix if the user does not provide the start time, the cmdlet will by default pick the latest snapshot's start time.
