### ISSUE TITLE
New-CohesityProtectionJob

### ISSUE THREAD

**Issue by komoreka** [cohesity/cohesity-powershell-module#49]
What is the param  when protecting view with this command to turn indexing on as by default is off?

**Comment by chirenjeet** [comment]
Unable to update protection-job using powershell module after cluster upgrade to version 6.3.1c

I'm using the version 1.0.13 powershell module.

-Unable to update the email address for alerts, rest of the properties seem to be working fine.

$protectionjob = Get-CohesityProtectionJob -Names <jobname>

$protectionjob.AlertingConfig.EmailAddresses = "abc.local.com" - This is not working. Either throws an error that the property is not available for some pretection-jobs or runs succesfully but does not updated the email address.

$protectionjob | Set-CohesityProtectionJob

Rest of the properties such as below works fine:

    $protectionjob.AlertingPolicy 
    $protectionjob.Priority 
    $protectionjob.IncrementalProtectionSlaTimeMins 
    $protectionjob.FullProtectionSlaTimeMins 
    $protectionjob.IndexingPolicy
