### ISSUE TITLE
Unable to update protection-job using powershell module after cluster upgrade to version 6.3.1c

### ISSUE THREAD

**Issue by chirenjeet** [cohesity/cohesity-powershell-module#54]
I'm using the version 1.0.13 powershell module.

-Unable to update the email address for alerts, rest of the properties seem to be working fine. I could update the .AlertingConfig.EmailAddresses property before the upgrade. 

$protectionjob = Get-CohesityProtectionJob -Names <jobname>
$protectionjob.AlertingConfig.EmailAddresses = "abc@local.com" - This is not working. Either throws an error that the property is not available for some protection-jobs or runs successfully but does not updated the email address.
$protectionjob | Set-CohesityProtectionJob

Rest of the properties such as below works fine:

    $protectionjob.AlertingPolicy 
    $protectionjob.Priority 
    $protectionjob.IncrementalProtectionSlaTimeMins 
    $protectionjob.FullProtectionSlaTimeMins 
    $protectionjob.IndexingPolicy

**Comment by ashish-cohesity** [comment]
Ack @chirenjeet , looks like there's a backward compatibility break with this particular field. Stand by , we are taking a decision on the fix soon.

**Comment by ashish-cohesity** [comment]
We are working on a fix, would be updating this in next release.

**Comment by ashish-cohesity** [comment]
This is fixed in our 1.1.1 release. Could you please try it again @chirenjeet . Closing this one.
