### ISSUE TITLE
Get-CohesityProtectionSource doesn't return as Object

### ISSUE THREAD

**Issue by DavidSeaton** [cohesity/cohesity-powershell-module#59]
I'm trying to do some workflow that requires the ID of the Protection Source.
When running Get-CohesityProtectionSource, it doesn't return an object that can be filters.
For example:
`Get-CohesityProtectionSource | ft Name`
Should return just the Names of the Protection Sources.
`Get-CohesityProtectionSource | where {$_.Name -like '*host*'}`
Should return any Production Sources that contain the name host.

Not sure how I'm to retrieve the Protection Source ID without a lot of custom parsing.

**Comment by ashish-cohesity** [comment]
Hi David, thanks for the feedback. The current versions are using generated models hence needs extra parsing. We are actively looking into fixing this and make it dead simple ..like you mentioned. 

For now you can use: 

`Get-CohesityProtectionSource |  ForEach-Object  { $_.RegistrationInfo.AccessInfo.Endpoint }`

`Get-CohesityProtectionSource |  where-object  { $_.RegistrationInfo.AccessInfo.Endpoint -like '*host*' }`

The $_ will autocomplete and suggest the the fields you want which are in nested format. I'm definitely tracking the above request for v2 of Powershell. Thanks for the feedback again.

**Comment by ashish-cohesity** [comment]
For source ID : 

 Get-CohesityProtectionSource |  ForEach-Object  { $_.RegistrationInfo.AccessInfo.Id  }

**Comment by DavidSeaton** [comment]
So I find this odd.
The `Get-CohesityProtectionSource` does not produce the same IDs as
`Get-CohesityProtectionSource | where-object { $_.RegistrationInfo.AccessInfo.Endpoint -like '*host*' }`
or
`Get-CohesityProtectionSource | ForEach-Object { $_.RegistrationInfo.AccessInfo.Id }`


This was the way i was able to retrieve the RegistrationInfo.AccessInfo.Id
```
PS C:\> $hostID = Get-CohesityProtectionSource | where-object { $_.RegistrationInfo.AccessInfo.Endpoint -like 'host1' }
| ForEach-Object { $_.RegistrationInfo.AccessInfo.Id }
```

Not sure how the two different IDs work.

**Comment by ashish-cohesity** [comment]
If you want protectionSourceID for other operations , use : 
```
Get-CohesityProtectionSource | where-object  { $_.RegistrationInfo.AccessInfo.Endpoint -like '*host1'}  | ForEach-Object { $_.ProtectionSource.Id}
```

Use that $_.ProtectionSource.Id ... AccessInfo ID is not used anywhere.
