### ISSUE TITLE
Server not reachable, could use better error handling on known issues

### ISSUE THREAD

**Issue by DavidSeaton** [cohesity/cohesity-powershell-module#64]
Get PowerShell error message when attempting to register a server that doesn't have it's ports open.

This is a misleading error message, the issues has been identified, however the error message implies something wrong with the CohesityModule or my command was at fault.

> PS C:\> Register-CohesityProtectionSourceHyperV -Server Server01 -HyperVType KHyperVHost
> Invoke-WebRequest : {"errorCode":"KInternalError","message":"Failed to connect to Server01. Error: Connection failure to Server01 during the call GetAgentInfo"}
> At C:\Program Files\WindowsPowerShell\Modules\Cohesity.PowerShell\1.1.1\Scripts\Utility\Invoke-RestApi.ps1:14 char:19
> \+ ...       $result = Invoke-WebRequest -UseBasicParsing @PSBoundParameters
> \+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
> ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
> At C:\Program Files\WindowsPowerShell\Modules\Cohesity.PowerShell\1.1.1\Scripts\Utility\Invoke-RestApi.ps1:16 char:31
> \+     return ($result.Content | ConvertFrom-Json)
> \+                               ~~~~~~~~~~~~~~~~
>     \+ CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
>     \+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

**Comment by ashish-cohesity** [comment]
Hi @DavidSeaton, Agree with you. Error should have pointed it out in a better way.  This response is coming from the API layer. Will pass on to the API team.
