### ISSUE TITLE
Copy-CohesityView : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Lioxxs** [cohesity/cohesity-powershell-module#82]
Dear team,

Using the latest version of Module Powershell 1.2.0 I get this return when trying to request a copy-CohesityView:

Copy-CohesityView : Object reference not set to an instance of an object.

example of command send:
`PS C:\Windows\system32> Copy-CohesityView -TaskName "clone-view-task" -SourceViewName "sourceview" -TargetViewName "clone-of-test-view" -TargetViewDescription "cloned view" -QosPolicy "Backup Target Low" -JobId 49402`

Same behaviour on your side?
Regards

**Comment by bijayprasadtiwari** [comment]
Will look into it and get back to you.

**Comment by Lioxxs** [comment]
Sorry my bad, wrong jobid  😒

**Comment by ashish-cohesity** [comment]
Hey @Lioxxs  no worries at all ...  to err is Developer :)

Keep the questions coming!
