### ISSUE TITLE
Copy-CohesityView not possible with DR view

### ISSUE THREAD

**Issue by Lioxxs** [cohesity/cohesity-powershell-module#88]
## 🐛 Bug Report

Copy-CohesityView is not possible with DR view, we get this message error : Copy-CohesityView : View with matching name not found

Seems because a dr view is labeled as inactive and you can get the id job through : Get-CohesityProtectionJob -OnlyInactive

## To Reproduce

1. get the job of the dr view : 
Get-CohesityProtectionJob -OnlyInactive

2. try to Copy-CohesityView with the job id from step1, you will have : View with matching name not found

## Expected behavior

the clone of dr with is available and works from GUI but should be also possible from pwercli command

thanks
regards.

**Comment by ashish-cohesity** [comment]
Ack . We are looking into this. @bijayprasadtiwari  can you please take a look.

**Comment by bijayprasadtiwari** [comment]
The bug is reproducible. Working on the solution.

**Comment by bijayprasadtiwari** [comment]
The fix is available in the release v1.4.0.

**Comment by bijayprasadtiwari** [comment]
Closing, the bug is fixed.
