### ISSUE TITLE
include stats for views

### ISSUE THREAD

**Issue by einarbey** [cohesity/cohesity-powershell-module#90]
Hi,

I have been digging in to api stats and i can se if you query view you can get storageConsumedBytes
/irisservices/api/v1/public/views?viewNames=[view name]&includeStats=true

but i can´t find this stats in powershell module 

can you add this stats to get-cohesityview ?

**Comment by ashish-cohesity** [comment]
Ack @einarbey, we are looking into this.

**Comment by bijayprasadtiwari** [comment]
The fix is available in v1.5.0.
